# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "IfIWere.me"
description: > # this means to ignore newlines until "email:"
   A mostly technical personal blog about anything and everything from development ideas, to home brewing, to DIY, to cooking, to photography and everything in between.

email: john.m.farrell1@gmail.com
#blog logo
logo: "/assets/images/logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/m50_flyover.jpg"

name: 'John Farrell'
author: 'John Farrell'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://johnmfarrell1.github.io" # the base hostname & protocol for your site
baseurl: "/blog"
#used to display twitter cards
twitter_handle: '@john_shm'

#fill in disqus shortname to use disqus
disqus: disqus_8HbhQw7z7P

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/john_shm
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/john.farrell.165685
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	linkedin
    url:	https://www.linkedin.com/in/john-farrell-51203255/
    desc:	LinkedIn
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/johnmfarrell1
    desc:	Github
    share_url:
    share_title:
    share_link:

  - icon:    beer
    url:    https://untappd.com/user/Johnmfarrell
    desc:    Untappd
    share_url:
    share_title:
    share_link:

  - icon:    envelope
    url:    mailto:john.m.farrell1@gmail.com
    desc:    email
    share_url:
    share_title:
    share_link:
